### ISSUE TITLE
Error when try to execute java tests

### ISSUE THREAD

**Issue by DarwinGonzalez** [devonfw/my-thai-star#414] opened 2021-07-28 07:52 UTC
### Expected behavior

As a developer, I want execute "mvn clean test" in order to generate a report on the test coverage.

### Actual behavior
It gives me the following error, and the report is not generated.

![imagen](https://user-images.githubusercontent.com/22544223/127284801-7c2f2e98-647f-42f4-a861-39c61c31cd42.png)

### Steps to reproduce (bug) 

1. Clone the repository
2. Execute "mvn clean test"

**Comment by ssarmokadam** [comment] 2022-06-02 09:37
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-62825383d986530011ae300d/issues/devonfw/my-thai-star/414?planning-poker) with ZenHub @isandesh1986

**Comment by sujith-mn** [comment] 2022-06-08 09:40
Could not reproduce this issue.. closing ..

**Closed by sujith-mn** 2022-06-08 09:40 UTC
Labels: bug, Team_Core
