### ISSUE TITLE
Start tagging working states

### ISSUE THREAD

**Issue by maybeec** [devonfw/my-thai-star#97] opened 2018-04-18 08:39 UTC
I just first tried mts to adapt an upcoming for it. However, I was not able to as the current version does not run properly and there is no recent release tag, which provides a working deployment state.
Please start to have a proper release management.

**Comment by hohwille** [comment] 2018-04-27 09:00
At least we introduce CI that should help us with quality and reduce build breaks (e.g. when merging PRs):
https://github.com/oasp/my-thai-star/pull/99

**Comment by sjimenez77** [comment] 2018-12-21 08:58
AFAIK this issue could be closed, right?

**Comment by hohwille** [comment] 2019-02-11 15:31
IMHO this could be considered as a duplicate of #123 and therefore closed.
@maybeec If you do not respond we will close this soon.

**Closed** 2019-02-11 16:03 UTC
Labels: bug
